name: CIX
favicon: null
layout_spectrum: 1
typography_spectrum: 0.12019
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#300608'
    - '#ffffff'
    - '#944a3f'
    - '#817e79'
    - '#ce9c83'
  brandStrength: 0.1875
  lightness: 0.5348055986687541
  saturation: 0.625
  rhythmicContrast: 0
purpose: []
