name: CIX
favicon: null
layout_spectrum: 1
typography_spectrum: 0.12019
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#3C493F'
    - '#7E8D85'
    - '#B3BFB8'
    - '#F0F7F4'
    - '#A2E3C4'
  brandStrength: 0.6131217791698873
  lightness: 0.5348055986687541
  saturation: 0.6681538338307291
  rhythmicContrast: 0.2879667249508202
purpose: []
